SUCCESS\
assertion holds: p.sum() == 3
